Web/PLF_Football.Web/Controllers/ClubsController.cs
namespace PLF_Football.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Clubs;

    [Authorize]
    public class ClubsController : BaseController
    {
        private readonly IClubsService clubService;

        public ClubsController(
            IClubsService clubService)
        {
            this.clubService = clubService;
        }

        public IActionResult Index(int id)
        {
            var viewModel = this.clubService.GetById<ClubMainVewModel>(id);
            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/FixturesController.cs
namespace PLF_Football.Web.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Common;
    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Fixtures;

    [Authorize]
    public class FixturesController : BaseController
    {
        private readonly IFixtureService fixtureService;
        private readonly IUsersService usersService;

        public FixturesController(
            IFixtureService fixtureService,
            IUsersService usersService)
        {
            this.fixtureService = fixtureService;
            this.usersService = usersService;
        }

        public IActionResult Index()
        {
            var allFixtures = this.fixtureService.GetAllFixtures<FixtureBasicViewModel>();
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var userteamId = this.usersService.GetFavoriteClubIdByUserId(userId);
            var viewModel = new CollectionOfFixturesViewModel
            {
                UserTeamId = userteamId,
                AllFixtures = allFixtures,
            };
            return this.View(viewModel);
        }

        public IActionResult Club(int clubId)
        {
            var fixtures = this.fixtureService
                .GetFixturesOnAndBeforeSpecificMatchdayByClub<FixtureBasicViewModel>(GlobalConstants.AllFixtureCount, clubId);

            var viewModel = new CollectionOfFixturesViewModel
            {
                AllFixtures = fixtures,
            };

            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/PlayersController.cs
namespace PLF_Football.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Common;
    using PLF_Football.Services;
    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Clubs;
    using PLF_Football.Web.ViewModels.Players;
    using PLF_Football.Web.ViewModels.PlayersPoints;
    using PLF_Football.Web.ViewModels.Position;

    [Authorize]
    public class PlayersController : BaseController
    {
        private readonly IPlayersService playersService;
        private readonly IClubsService clubsService;
        private readonly IPositionService positionService;
        private readonly IPlayersPointsService playersPointsService;
        private readonly IFixtureScraperService fixtureScraperService;

        public PlayersController(
            IPlayersService playersService,
            IClubsService clubsService,
            IPositionService positionService,
            IPlayersPointsService playersPointsService,
            IFixtureScraperService fixtureScraperService)
        {
            this.playersService = playersService;
            this.clubsService = clubsService;
            this.positionService = positionService;
            this.playersPointsService = playersPointsService;
            this.fixtureScraperService = fixtureScraperService;
        }

        public IActionResult Profile(int id)
        {
            var viewModel = this.playersService.GetPlayerById<PlayerProfileViewModel>(id);
            viewModel.Age = (int)(DateTime.Now.Year - viewModel.DateOfBirth?.Year);
            if (DateTime.Now.Date < viewModel.DateOfBirth?.AddYears(viewModel.Age))
            {
                viewModel.Age--;
            }

            return this.View(viewModel);
        }

        public IActionResult Statistics(int id)
        {
            var clubName = this.playersService.GetClubNameByPLayerId(id);
            var clubId = this.clubsService.GetClubIdByClubName(clubName);

            var viewModel = this.playersService.GetPlayerStatsbyId<PlayerStatsViewModel>(id);
            viewModel.ClubName = clubName;
            viewModel.ClubId = clubId;

            return this.View(viewModel);
        }

        public IActionResult All(int clubId, int positionId, string searchString, int page = 1)
        {
            var viewModel = new AllPlayersCollectionViewModel
            {
                PositionSearch = positionId,
                ClubSearch = clubId,
                SearchString = searchString,
                PageNumber = page,
                ItemsPerPage = GlobalConstants.PlayersPerPage,
                AllPlayers = this.playersService.GetAll<PlayerForAllPlayersViewModel>(),
                Positions = this.positionService.GetAll<PositionBasicViewModel>(),
                Clubs = this.clubsService.GetAll<ClubBasicViewModel>(),
            };

            viewModel.ItemsCount = viewModel.AllPlayers.Count;
            viewModel.Positions.Add(new PositionBasicViewModel { Name = "All positions", Id = -1 });
            viewModel.Positions = viewModel.Positions.OrderBy(x => x.Id).ToList();
            viewModel.Clubs.Add(new ClubBasicViewModel { Name = "All clubs", Id = -1 });
            viewModel.Clubs = viewModel.Clubs.OrderBy(x => x.Id).ToList();

            if (viewModel.PageNumber < 1)
            {
                viewModel.PageNumber = 1;
            }
            else if (viewModel.PageNumber > viewModel.PagesCount)
            {
                viewModel.PageNumber = viewModel.PagesCount;
            }

            if (clubId > 0)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.Club.Id == clubId).ToList();
            }

            if (positionId > 0)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.Position.Id == positionId).ToList();
            }

            if (searchString != null)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.FullName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> Points(int id)
        {
            var pointsByFixture = this.playersPointsService.GetAllPointsByMatchdaysForPlayer<PointsByFixtureViewModel>(id);
            var lastMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();
            for (int i = 13; i < lastMatchday; i++)
            {
                if (!pointsByFixture.Any(x => x.Matchday == i))
                {
                    pointsByFixture.Add(new PointsByFixtureViewModel { Matchday = i, Points = 0 });
                }
            }

            var clubName = this.playersService.GetClubNameByPLayerId(id);
            var playerFullName = this.playersService.GetPlayerFullNameById(id);
            var clubId = this.clubsService.GetClubIdByClubName(clubName);
            var viewModel = new PlayerPointsViewModel
            {
                PlayerId = id,
                PlayerName = playerFullName,
                ClubName = clubName,
                ClubId = clubId,
                PointsByFixture = pointsByFixture.OrderBy(x => x.Matchday).ToList(),
            };

            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/UsersController.cs
namespace PLF_Football.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Services;
    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.ApplicationUsers;
    using PLF_Football.Web.ViewModels.Fixtures;
    using PLF_Football.Web.ViewModels.Players;
    using PLF_Football.Web.ViewModels.UserGame;

    [Authorize]
    public class UsersController : BaseController
    {
        private const int FirstMatchday = 1;

        private readonly IUserGamesService userGamesService;
        private readonly IUsersService usersService;
        private readonly IFixtureService fixtureService;
        private readonly IFixtureScraperService fixtureScraperService;

        public UsersController(
            IUserGamesService userGamesService,
            IUsersService usersService,
            IFixtureService fixtureService,
            IFixtureScraperService fixtureScraperService)
        {
            this.userGamesService = userGamesService;
            this.usersService = usersService;
            this.fixtureService = fixtureService;
            this.fixtureScraperService = fixtureScraperService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var nextMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();

            var previousMatchday = nextMatchday - 2;
            var viewModel = this.usersService.GetUserById<UserIndexPageViewModel>(userId);

            viewModel.Id = userId;
            viewModel.Teams = this.userGamesService
                        .GetUserGamesByUserIdAfterSpecificMatchday<UserGameTeamViewModel>(userId, FirstMatchday);
            viewModel.LastStartedMatchday = nextMatchday - 1;

            foreach (var matchday in viewModel.Teams)
            {
                if (matchday.Matchday < nextMatchday)
                {
                    matchday.IsMatchdayStarted = true;
                }
            }

            var fixtures = this.fixtureService.GetFixturesAfterSpecificAndBeforeOrOnNextMatchday<FixtureBasicViewModel>(previousMatchday, nextMatchday);

            viewModel.Fixtures = fixtures;

            return this.View(viewModel);
        }

        public async Task<IActionResult> AllTeams(string userId = null)
        {
            if (userId == null)
            {
                userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }

            var viewModel = this.usersService.GetUserById<UserAllTeamsViewModel>(userId);
            var nextMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();
            foreach (var matchday in viewModel.Teams)
            {
                if (matchday.Matchday < nextMatchday)
                {
                    matchday.IsMatchdayStarted = true;
                }
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> Team(int matchday, string addResult = null)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var viewModel = this.userGamesService.GetUserGame<UserGameTeamViewModel>(userId, matchday);
            if (viewModel == null)
            {
                viewModel = new UserGameTeamViewModel
                {
                    UserId = userId,
                    Matchday = matchday,
                    Team = new List<UserTeamPlayerViewModel>(),
                };
            }

            viewModel.AddPlayerResult = addResult;
            var nextMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();
            if (viewModel.Matchday < nextMatchday)
            {
                viewModel.IsMatchdayStarted = true;
            }

            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Views/Users/AllTeams.cshtml
@model PLF_Football.Web.ViewModels.ApplicationUsers.UserAllTeamsViewModel

@using System.Security.Claims;

@{
    this.ViewData["ClubImg"] = @Model.FavoriteTeamName.ToLower();
    this.ViewData["Title"] = @Model.UserName +"'s "+ @Model.FavoriteTeamName + " Fantasy Teams";
    this.ViewData["CuurentUserId"] = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
}
<style>
    .bg-team::after {
        content: "";
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        background-image: url('/image/Club/@(this.ViewData["ClubImg"]).png');
        width: 100%;
        height: 100%;
        background-position: center;
        background-size: 100%;
        opacity: 0.3;
        z-index: -1;
    }
    .btn-add{
        margin-right: 10px;
    }
</style>
<div class="bg-team">
    <br />
    <div class="d-flex justify-content-between">
        <span  style="font-weight:bolder; font-style:italic">@Model.UserName Total Points: @Model.TotalPoints</span>
        <h2>@this.ViewData["Title"]</h2>
    </div>
    <br />
    <hr />
    <div>
        <div class="col-md-12 text-center" style="font-weight:bolder">
            @foreach (var userGame in Model.Teams.Where(z=>z.Team.Count > 0 ).OrderByDescending(x => x.Matchday))
            {
            <div class="row align-items-center">

                <span class="col-md-2 alert-dark">Matchweek: @userGame.Matchday </span>
                @if (userGame.IsMatchdayStarted)
                {
                    <span class="col-md-2 alert-danger ">Status: Closed</span>
                }
                else
                {
                    <span class="col-md-2 alert-success ">Status: Open</span>
                }
                <span></span>
                <span class="col-md-4 alert-dark">Team: @userGame.Team.Count players -  Price: @userGame.TeamSumAsString </span>
                <span class="col-md-1 alert-dark">pts: @userGame.Points</span>
                <span class="row justify-content-end col-md-3">
                    @if (userGame.UserId == (string)this.ViewData["CuurentUserId"])
                    {
                        @if (!userGame.IsMatchdayStarted && userGame.Team.Count < 11)
                        {
                            <a class="btn btn-dark alert-success btn-add" style="font-weight:bolder" asp-controller="Players" asp-action="All">
                                Add Player
                            </a>
                        }
                        else
                        {
                            <a class="btn btn-dark alert-success btn-add" style="font-weight:bolder" asp-controller="UserGames" asp-action="CopyTeam" asp-route-userGameId="@userGame.Id">
                                Copy team
                            </a>
                        }
                        <a class="btn btn-dark alert-secondary" style="font-weight:bolder" asp-controller="Users" asp-action="Team"
                           asp-route-matchday="@userGame.Matchday">
                            Details
                        </a>
                    }
                </span>
            </div>
                <br />
                <div class="col-md-12 d-flex justify-content-between">
                    @foreach (var player in userGame.Team.OrderByDescending(x => x.Position.Id))
                    {
                     <a title="@player.LastName - @player.ClubName" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                        <img style="height:100px" src="@player.ImageUrl" alt="Alternate Text" />

                        @if (player.PlayerPoints.Any(x => x.Matchday == userGame.Matchday))
                        {
                             <p>
                                 pts: @player.PlayerPoints.Where(x => x.Matchday == userGame.Matchday).Select(x => x.Points).FirstOrDefault()
                             </p>
                        }
                        else 
                        {
                             <p>
                                 pts: 0
                             </p>
                        }

                     </a>
                     }
                </div>
                <hr />
            }
        </div>
    </div>
</div>

Web/PLF_Football.Web/Views/Users/Index.cshtml
@model PLF_Football.Web.ViewModels.ApplicationUsers.UserIndexPageViewModel
@{ 
    this.ViewData["0"] = "Previous";
    this.ViewData["1"] = "Current";
    this.ViewData["2"] = "Next";
}
<style>
    .bg-user::after {
        content: "";
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        background-image: url('/image/Common/tactics.png');
        width: 100%;
        height: 100%;
        background-position: center;
        background-size: 100%;
        opacity: 0.3;
        z-index: -1;
        }

    .buttons{
            position: absolute;
            top: 190px;
            right:  25px;
            display: flex;
            flex-direction: column;
        }
    .buttons a{
            margin-bottom: 10px;
            width: 160px;
        }
    .matchday {
            background-color: grey;
            color: black;
            font-weight: bold;
            height: 30px;
            border-radius: 10px;
            margin:10px 0;
            padding-top: 3px;
        }
    .team {
            padding: 10px 0px 15px 25px;
            width: 350px;
            height: 460px;
            background-color: forestgreen;
            border-radius:10px;
        }
    .team-info{
        color: lightgreen;
    }
    .btn-small{
            font-size: 16px;
            padding: 3px 5px;
            border-radius: 3px;
        }
     div a p{
            color: lightgreen;
            font-size: 20px;
        }
    .span-center{
        margin: 120px 60px;
        font-size: 22px;
        color: lightgreen;
        text-align: center;
    }
    .fixture {
        margin-top: 10px;
        background-color: grey;
        border-radius: 10px;    
        padding-top: 8px;
    }
    .fixture .row{
        min-height: 45px;
        align-items: center;
        
    }
    .fixture-team{
        font-size: 15px;
        color: black;
        font-weight: bold;
    }
    .fixture-result{
        font-size: 13px;
        font-weight: bold;  
        color: white;
        padding: 0 0;
    }
    .right{
        text-align: end;
    }
    hr{
        margin: 8px 16px;
    }
    .count{
        margin-left: -25px;
    }

</style>

    <div class="bg-user">

        <div class="buttons">

            <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="Supporters" asp-action="AllByTotalPoints">
                Total Pts: @Model.TotalPoints
            </a>
            <br />
            <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="Users" asp-action="AllTeams">
                My All Teams
            </a>

            @if (Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday + 1).FirstOrDefault()== null || Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday + 1).FirstOrDefault()?.Team.Count() < 11)
            {
                <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="Players" asp-action="All">
                    Add Player
                </a>
            }
            @if (Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday + 1).FirstOrDefault()?.Team.Count() > 0)
            {
                <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="Users" asp-action="Team" asp-route-userId="@Model.Id" asp-route-matchday="@(Model.LastStartedMatchday +1)">
                    Remove Player
                </a>
            }

            <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="" asp-action="Chat">
                Chat
            </a>

            <br />
            <a class="btn btn-primary alert-secondary" style="font-weight:bolder" asp-controller="Fixtures" asp-action="Club" asp-route-clubId="@Model.FavoriteTeamId">
                <div>@Model.FavoriteTeamName</div>
                <div>Fixtures</div>
            </a>

        </div>
        
        <div class="row">
            @for (int i = 0; i < 3; i++)
            {
                <div class="col-md-4">

                    <div class="text-center matchday">Matchweek: @(Model.LastStartedMatchday-1+i) (@this.ViewData[$"{i}"])</div>

                    <div class="team">
                        @if (Model.Teams.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                        {
                            <div class="row align-items-center">

                                <span class="col-md-6 team-info">Team: @Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().TeamSumAsString </span>
                                <span class="col-md-3 team-info">Pts: @Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Points</span>
                                <a class="btn-small alert-success" style="font-weight:bolder" asp-controller="Users" asp-action="Team" asp-route-matchday="@(Model.LastStartedMatchday-1+i)">
                                    Details
                                </a>
                            </div>
                            <br />
                            <div class="row col-md-12 justify-content-around" style="min-height:70px">

                                @foreach (var player in Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Team.Where(x => x.Position.Id == 1))
                                {
                                    <a class="row" title="@player.LastName - @player.ClubName" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                        <img style="height:70px" src="@player.ImageUrl" alt="Alternate Text" />

                                        @if (player.PlayerPoints.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                                        {
                                            <p>
                                                @player.PlayerPoints.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).Select(x => x.Points).FirstOrDefault()
                                            </p>
                                        }
                                        else
                                        {
                                            <p>
                                                0
                                            </p>
                                        }

                                    </a>

                                }

                            </div>
                            <br />
                            <div class="row col-md-12 justify-content-around" style="min-height:70px">

                                @foreach (var player in Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Team.Where(x => x.Position.Id == 2))
                                {
                                    <a class="row" title="@player.LastName - @player.ClubName" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                        <img style="height:70px" src="@player.ImageUrl" alt="Alternate Text" />

                                        @if (player.PlayerPoints.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                                        {
                                            <p>
                                                @player.PlayerPoints.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).Select(x => x.Points).FirstOrDefault()
                                            </p>
                                        }
                                        else
                                        {
                                            <p>
                                                0
                                            </p>
                                        }

                                    </a>

                                }

                            </div>
                            <br />
                            <div class="row col-md-12 justify-content-around" style="min-height:70px">

                                @foreach (var player in Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Team.Where(x => x.Position.Id == 3))
                                {
                                    <a class="row" title="@player.LastName - @player.ClubName" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                        <img style="height:70px" src="@player.ImageUrl" alt="Alternate Text" />

                                        @if (player.PlayerPoints.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                                        {
                                            <p>
                                                @player.PlayerPoints.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).Select(x => x.Points).FirstOrDefault()
                                            </p>
                                        }
                                        else
                                        {
                                            <p>
                                                0
                                            </p>
                                        }

                                    </a>

                                }

                            </div>
                            <br />
                            <div class="row col-md-12 justify-content-around" style="min-height:70px">

                                @foreach (var player in Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Team.Where(x => x.Position.Id == 4))
                                {
                                    <a class="row" title="@player.LastName - @player.ClubName" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                        <img style="height:70px" src="@player.ImageUrl" alt="Alternate Text" />

                                        @if (player.PlayerPoints.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                                        {
                                            <p>
                                                @player.PlayerPoints.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).Select(x => x.Points).FirstOrDefault()
                                            </p>
                                        }
                                        else
                                        {
                                            <p>
                                                0
                                            </p>
                                        }

                                    </a>

                                }
                            </div>
                            <hr/>
                            <div class="team-info text-center count">
                                Players in team: <b>@Model.Teams.Where(x => x.Matchday == Model.LastStartedMatchday - 1 + i).FirstOrDefault().Team.Count</b>
                            </div>
                        }
                        else
                        {
                            <div class="span-center">Sorry, you don`t have a team for this matchweek!</div>
                        }
                    </div>

                    <div class="fixture col-md-12">
                        @if (Model.Fixtures.Any(x => x.Matchday == Model.LastStartedMatchday - 1 + i))
                        {
                            foreach (var fix in Model.Fixtures.Where(x=>x.Matchday == Model.LastStartedMatchday - 1 + i).OrderBy    (x=>x.Result).ToList())
                            {
                                <div class="row" @if (Model.FavoriteTeamId == fix.AwayTeamId || Model.FavoriteTeamId== fix.HomeTeamId) {<text> style="background-color: forestgreen" </text> }>
                                    <a class="col-md-5 fixture-team left" asp-controller="Clubs" asp-action="Index" asp-route-id="@fix.HomeTeamId" >
                                        @fix.HomeTeamName
                                    </a>

                                    <div class="col-md-2 fixture-result text-center" @if (!fix.Finished) {<text>                style="color:darkgray" </text> }>
                                        @fix.Result
                                        @if (fix.Result.Contains(":")) { <div>(CET)</div> }
                                    </div>

                                    <a  class="col-md-5 fixture-team right" asp-controller="Clubs" asp-action="Index" asp-route-id="@fix.AwayTeamId">
                                        @fix.AwayTeamName
                                    </a>
                                </div>
                                <hr />
                            }
                        }
                        else
                        {
                            <div class="span-center">Not fixture in this matchday!</div>
                        }
                    </div>
                </div>
            }
        </div>
    </div>