Web/PLF_Football.Web/Controllers/ClubsController.cs
namespace PLF_Football.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Clubs;

    [Authorize]
    public class ClubsController : BaseController
    {
        private readonly IClubsService clubService;

        public ClubsController(
            IClubsService clubService)
        {
            this.clubService = clubService;
        }

        public IActionResult Index(int id)
        {
            var viewModel = this.clubService.GetById<ClubMainVewModel>(id);
            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/FixtureController.cs
namespace PLF_Football.Web.Controllers
{
    using PLF_Football.Services.Data;

    public class FixtureController : BaseController
    {
        private readonly IFixtureService fixtureService;

        public FixtureController(IFixtureService fixtureService)
        {
            this.fixtureService = fixtureService;
        }
    }
}

Web/PLF_Football.Web/Controllers/FixturesController.cs
namespace PLF_Football.Web.Controllers
{
    using System.Security.Claims;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Common;
    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Fixtures;

    [Authorize]
    public class FixturesController : BaseController
    {
        private readonly IFixtureService fixtureService;
        private readonly IUsersService usersService;

        public FixturesController(
            IFixtureService fixtureService,
            IUsersService usersService)
        {
            this.fixtureService = fixtureService;
            this.usersService = usersService;
        }

        public IActionResult Index()
        {
            var allFixtures = this.fixtureService.GetAllFixtures<FixtureBasicViewModel>();
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var userteamId = this.usersService.GetFavoriteClubIdByUserId(userId);
            var viewModel = new CollectionOfFixturesViewModel
            {
                UserTeamId = userteamId,
                AllFixtures = allFixtures,
            };
            return this.View(viewModel);
        }

        public IActionResult Club(int clubId)
        {
            var fixtures = this.fixtureService
                .GetFixturesOnAndBeforeSpecificMatchdayByClub<FixtureBasicViewModel>(GlobalConstants.AllFixtureCount, clubId);

            var viewModel = new CollectionOfFixturesViewModel
            {
                AllFixtures = fixtures,
            };

            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/PlayersController.cs
namespace PLF_Football.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Common;
    using PLF_Football.Services;
    using PLF_Football.Services.Data;
    using PLF_Football.Web.ViewModels.Clubs;
    using PLF_Football.Web.ViewModels.Players;
    using PLF_Football.Web.ViewModels.PlayersPoints;
    using PLF_Football.Web.ViewModels.Position;

    [Authorize]
    public class PlayersController : BaseController
    {
        private readonly IPlayersService playersService;
        private readonly IClubsService clubsService;
        private readonly IPositionService positionService;
        private readonly IPlayersPointsService playersPointsService;
        private readonly IFixtureScraperService fixtureScraperService;

        public PlayersController(
            IPlayersService playersService,
            IClubsService clubsService,
            IPositionService positionService,
            IPlayersPointsService playersPointsService,
            IFixtureScraperService fixtureScraperService)
        {
            this.playersService = playersService;
            this.clubsService = clubsService;
            this.positionService = positionService;
            this.playersPointsService = playersPointsService;
            this.fixtureScraperService = fixtureScraperService;
        }

        public IActionResult Profile(int id)
        {
            var viewModel = this.playersService.GetPlayerById<PlayerProfileViewModel>(id);
            viewModel.Age = (int)(DateTime.Now.Year - viewModel.DateOfBirth?.Year);
            if (DateTime.Now.Date < viewModel.DateOfBirth?.AddYears(viewModel.Age))
            {
                viewModel.Age--;
            }

            return this.View(viewModel);
        }

        public IActionResult Statistics(int id)
        {
            var clubName = this.playersService.GetClubNameByPLayerId(id);
            var clubId = this.clubsService.GetClubIdByClubName(clubName);

            var viewModel = this.playersService.GetPlayerStatsbyId<PlayerStatsViewModel>(id);
            viewModel.ClubName = clubName;
            viewModel.ClubId = clubId;

            return this.View(viewModel);
        }

        public IActionResult All(int clubId, int positionId, string searchString, int page = 1)
        {
            var viewModel = new AllPlayersCollectionViewModel
            {
                PositionSearch = positionId,
                ClubSearch = clubId,
                SearchString = searchString,
                PageNumber = page,
                ItemsPerPage = GlobalConstants.PlayersPerPage,
                AllPlayers = this.playersService.GetAll<PlayerForAllPlayersViewModel>(),
                Positions = this.positionService.GetAll<PositionBasicViewModel>(),
                Clubs = this.clubsService.GetAll<ClubBasicViewModel>(),
            };

            viewModel.ItemsCount = viewModel.AllPlayers.Count;
            viewModel.Positions.Add(new PositionBasicViewModel { Name = "All positions", Id = -1 });
            viewModel.Positions = viewModel.Positions.OrderBy(x => x.Id).ToList();
            viewModel.Clubs.Add(new ClubBasicViewModel { Name = "All clubs", Id = -1 });
            viewModel.Clubs = viewModel.Clubs.OrderBy(x => x.Id).ToList();

            if (viewModel.PageNumber < 1)
            {
                viewModel.PageNumber = 1;
            }
            else if (viewModel.PageNumber > viewModel.PagesCount)
            {
                viewModel.PageNumber = viewModel.PagesCount;
            }

            if (clubId > 0)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.Club.Id == clubId).ToList();
            }

            if (positionId > 0)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.Position.Id == positionId).ToList();
            }

            if (searchString != null)
            {
                viewModel.AllPlayers = viewModel.AllPlayers.Where(x => x.FullName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> Points(int id)
        {
            var pointsByFixture = this.playersPointsService.GetAllPointsByMatchdaysForPlayer<PointsByFixtureViewModel>(id);
            var lastMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();
            for (int i = 13; i < lastMatchday; i++)
            {
                if (!pointsByFixture.Any(x => x.Matchday == i))
                {
                    pointsByFixture.Add(new PointsByFixtureViewModel { Matchday = i, Points = 0 });
                }
            }

            var clubName = this.playersService.GetClubNameByPLayerId(id);
            var playerFullName = this.playersService.GetPlayerFullNameById(id);
            var clubId = this.clubsService.GetClubIdByClubName(clubName);
            var viewModel = new PlayerPointsViewModel
            {
                PlayerId = id,
                PlayerName = playerFullName,
                ClubName = clubName,
                ClubId = clubId,
                PointsByFixture = pointsByFixture.OrderBy(x => x.Matchday).ToList(),
            };

            return this.View(viewModel);
        }
    }
}

Web/PLF_Football.Web/Controllers/UserGamesController.cs
namespace PLF_Football.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using PLF_Football.Common;
    using PLF_Football.Data.Models;
    using PLF_Football.Services;
    using PLF_Football.Services.Data;

    [Authorize]
    public class UserGamesController : BaseController
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserGamesService userGamesService;
        private readonly IPlayersService playersService;
        private readonly IFixtureScraperService fixtureScraperService;

        public UserGamesController(
            UserManager<ApplicationUser> userManager,
            IUserGamesService userGamesService,
            IPlayersService playersService,
            IFixtureScraperService fixtureScraperService)
        {
            this.userManager = userManager;
            this.userGamesService = userGamesService;
            this.playersService = playersService;
            this.fixtureScraperService = fixtureScraperService;
        }

        public async Task<IActionResult> AddPlayer(int id)
        {
            var currUser = await this.userManager.GetUserAsync(this.User);
            var nextMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();

            var userGameId = this.userGamesService.GetUserGameIdByUserAndMatchday(currUser.Id, nextMatchday);

            if (userGameId == 0 && nextMatchday < 39)
            {
                userGameId = await this.userGamesService.CreateUserGameAsync(currUser.Id, nextMatchday);
            }

            var userGameUserId = this.userGamesService.GetUserIdByUserGameId(userGameId);
            if (currUser.Id != userGameUserId)
            {
                return this.Unauthorized();
            }

            var player = this.playersService.GetPlayerById(id);
            var playersInTeam = this.userGamesService.GetUserGameMatchTeamPlayers(userGameId);
            var teamPrice = playersInTeam.Sum(x => x.Price);
            var addResult = string.Empty;
            try
            {
                if (playersInTeam.Count >= 11)
                {
                    throw new System.Exception("Your team si full!");
                }
                else if (playersInTeam.Contains(player))
                {
                    throw new System.Exception("This player has already been added!");
                }
                else if (currUser.ClubId == player.ClubId
                    && playersInTeam.Where(x => x.ClubId == currUser.ClubId).Count() >= 5)
                {
                    throw new System.Exception("You already have 5 players from your favorite team!");
                }
                else if (currUser.ClubId != player.ClubId
                    && playersInTeam.Where(x => x.ClubId != currUser.ClubId).Count() >= 6)
                {
                    throw new System.Exception("You already have 6 players from other teams!");
                }

                // Gk
                else if (player.PositionId == 4
                    && playersInTeam.Where(x => x.PositionId == 4).Count() >= 1)
                {
                    throw new System.Exception("You already have a goalkeeper in your team!");
                }

                // Def
                else if (player.PositionId == 3
                    && playersInTeam.Where(x => x.PositionId == 3).Count() >= 4)
                {
                    throw new System.Exception("You already have 4 defenders in your team!");
                }

                // Midf
                else if (player.PositionId == 2
                    && playersInTeam.Where(x => x.PositionId == 2).Count() >= 4)
                {
                    throw new System.Exception("You already have 4 midfielders in your team!");
                }

                // Forw
                else if (player.PositionId == 1
                    && playersInTeam.Where(x => x.PositionId == 1).Count() >= 2)
                {
                    throw new System.Exception("You already have 2 forwards in your team!");
                }
                else if (GlobalConstants.UserBudget - teamPrice < player.Price)
                {
                    throw new System.Exception("Not enough money to buy this player!");
                }
                else
                {
                    await this.userGamesService.AddPlayerToUserGameAsync(id, userGameId);
                    addResult = "Player successfuly added.";
                }
            }
            catch (System.Exception ex)
            {
                addResult = ex.Message;
            }

            return this.Redirect($"/Users/Team/?matchday={nextMatchday}&addResult={addResult}");
        }

        public async Task<IActionResult> Remove(int playerId, int userGameId)
        {
            var currUser = await this.userManager.GetUserAsync(this.User);
            var userGameUserId = this.userGamesService.GetUserIdByUserGameId(userGameId);
            if (currUser.Id != userGameUserId)
            {
                return this.Unauthorized();
            }

            await this.userGamesService.RemovePlayerFromUserGameAsync(playerId, userGameId);
            var matchday = this.userGamesService.GetMatchdayByuserGameId(userGameId);
            return this.Redirect($"/Users/Team/?matchday={matchday}");
        }

        public async Task<IActionResult> CopyTeam(int userGameId)
        {
            var userGameUserId = this.userGamesService.GetUserIdByUserGameId(userGameId);
            var currenUser = await this.userManager.GetUserAsync(this.User);
            if (userGameUserId != currenUser.Id)
            {
                return this.Unauthorized();
            }

            var playersIds = this.userGamesService.GetPlayersIdsByUserGameId(userGameId);

            var nextMatchday = await this.fixtureScraperService.GetFirstNotStartedMatchdayAsync();
            var userGameIdForNextMatchday = this.userGamesService.GetUserGameIdByUserAndMatchday(currenUser.Id, nextMatchday);

            if (userGameIdForNextMatchday > 0
                &&
                this.userGamesService.GetUserGameMatchTeamPlayers(userGameIdForNextMatchday).Count > 0)
            {
                return this.RedirectToAction("Team", "Users", new { matchday = nextMatchday, addResult = "Your team must be empty to copy another team!" });
            }

            foreach (var playerId in playersIds)
            {
                await this.AddPlayer(playerId);
            }

            return this.RedirectToAction("Team", "Users", new { matchday = nextMatchday, addResult = "Team players successfuly added." });
        }
    }
}

Web/PLF_Football.Web/Views/Clubs/ById.cshtml
@model PLF_Football.Web.ViewModels.Clubs.ClubMainVewModel
@{
    this.ViewData["ClubImg"] = @Model.Name.ToLower();
}

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="~/css/teamSection.css" rel="stylesheet" />
    <!------ Include the above in your HEAD tag ---------->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .club-info::after {
            content: "";
            display: block;
            position: absolute;
            top: -10%;
            left: -10%;
            background-image: url('/image/Club/@(this.ViewData["ClubImg"]).png');
            width: 120%;
            height: 120%;
            background-position: center;
            background-size: 100%;
            opacity: 0.6;
            z-index: -1;
        }
    </style>

    <section class="our-webcoderskull padding-lg">

        <div class="container container-players">

            <div class="club-info">

                <div>
                    <img src="@Model.BadgeUrl" alt="alternate text" style="height:50px; width:50px"/>
                    <span class="display-4" >@Model.Name</span>
                </div>

                <div>
                    <ul class="row follow-us clearfix">
                        <li>
                            <a href="@Model.SocialLinks.WebsiteLink">
                                <i class="fas fa-home" aria-hidden="true"></i>
                                <span>Official Website</span>
                            </a>
                        </li>
                        <li>
                            <a href="@Model.SocialLinks.FacebookLink">
                                <i class="fa fa-facebook" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li>
                            <a href="@Model.SocialLinks.TweeterLink">
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </a>
                        </li>
                        <li>
                            <a href="@Model.SocialLinks.InstagramLink">
                                <i class="fa fa-linkedin" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                </div>

                <div>
                    <a href="@Model.PLLink">source</a>
                </div>

                <div>
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <span>@Model.StadiumName</span>
                </div>
            </div>

            <ul class="row container-players">

                @foreach (var player in Model.Players.Where(x=>x.SquadNumber != null).OrderByDescending(x => x.Position.Id).ThenBy(x=>int.Parse(x.SquadNumber)))
                {
                    <li class="col-12 col-md-6 col-lg-3 accept-policy" style="background-color:transparent">
                        <div class="cnt-block equal-hight border-bottom box-shadow" style="height: 389px;">

                            <span class="number">@player.SquadNumber</span>
                            <figure>
                                <img src="@player.ImageUrl" class="img-responsive" alt="" onerror="this.src = 'https://resources.premierleague.com/premierleague/photos/players/110x140/Photo-Missing.png'">
                            </figure>

                            <a class="btn button-player-card alert-success" asp-controller="UserGames" asp-action="AddPlayer" asp-route-id="@player.Id">
                                Buy
                            </a>

                            <p style="color:crimson">@player.PriceAtString</p>
                            <h3 class="display-2">@player.FullName</h3>
                            <p class="display-3">@player.PositionName <i style="color: grey"> @player.Country.Name</i></p>

                            <p>
                                <a class="btn btn-secondary alert-secondary" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                    Profile
                                </a>
                            </p>
                            <ul class="follow-us clearfix">
                                @if (player.SocialLinks.FacebookLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.FacebookLink">
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }
                                @if (player.SocialLinks.TweeterLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.TweeterLink">
                                            <i class="fa fa-twitter" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }
                                @if (player.SocialLinks.InstagramLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.InstagramLink">
                                            <i class="fa fa-instagram" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }

                            </ul>
                            <br />
                            <br />
                        </div>
                    </li>

                };
            </ul>

        </div> 

    </section>

Web/PLF_Football.Web/Views/Clubs/Fixtures.cshtml
@model PLF_Football.Web.ViewModels.Fixtures.CollectionOfFixturesViewModel

    <style>
        .container{
            margin: 0 15px;
            max-width: 95vw;
        }
        .container-fixture{
            max-height: 1000px;
            display: flex;
            flex-direction: column;
            flex-wrap:wrap;
            padding-top: 30px;
        }
        .fixture {
            min-height: 60px;
            margin: 0 10px;
            align-items: center;
            background-color: lightgray;
            border-radius: 10px;
        }
        .fixture-team {
            font-size: 14px;
            color: black;
            font-weight: bold;
        }

        .fixture-result {
            font-size: 20px;
            font-weight: bold;
            color: firebrick;
            padding: 0 0;
        }

        .right {
            text-align: end;
        }
        hr{
            margin: 5px 25px;
        }
    </style>
    <div class="col container-fixture">
        @foreach (var fix in Model.AllFixtures.OrderBy(x => x.Matchday))
        {
            <div class="row col-md-4 fixture">
                <a class="col-md-5 fixture-team left" asp-controller="Clubs" asp-action="Index" asp-route-id="@fix.HomeTeamId">
                    @fix.HomeTeamName
                </a>

                <span class="col-md-2 text-center fixture-result" @if (!fix.Finished) { <text> style="color:green" </text> }>
                    @if (fix.Result.Contains(":"))
                     {
                        <text> M: </text> @fix.Matchday
                    }
                    else
                    {
                        @fix.Result
                    }
                </span>

                <a class="col-md-5 fixture-team right" asp-controller="Clubs" asp-action="Index" asp-route-id="@fix.AwayTeamId">
                    @fix.AwayTeamName
                </a>
            </div>
            <hr />
        }
    </div>

Web/PLF_Football.Web/Views/Clubs/Index.cshtml
@model PLF_Football.Web.ViewModels.Clubs.ClubMainVewModel
@{
    this.ViewData["ClubImg"] = @Model.Name.ToLower();
}

    <link href="~/css/teamSection.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .club-info::after {
            content: "";
            display: block;
            position: absolute;
            top: -10%;
            left: -10%;
            background-image: url('/image/Club/@(this.ViewData["ClubImg"]).png');
            width: 120%;
            height: 120%;
            background-position: center;
            background-size: 100%;
            opacity: 0.6;
            z-index: -1;
        }
        .club-info{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }
        .club-nav{
            display: flex;
            flex-direction: column;
            margin-left: -90px;

        }
        .club-nav a{
            width: 160px;
            margin-bottom: 20px;

            color: black;
            font-size: 20px;
            font-weight: bold;
        }
        .team-badge img{
            width: 160px;
            height: 160px;
            margin: 0 0 40px 0;
        }
        .club-content{
            display: flex;
            flex-direction: column;
            justify-content: start;
        }
        .club-content div{
            margin-left: auto;
            font-size: 24px;
            margin-bottom: 10px;
        }
        .team-sl{
            background-color: rgba(0, 0, 0, 0.6);
            border-radius: 30px;
        }
        .club-content .team-sl a {
            text-decoration: none;
        }
        .club-content .fa {
            color: white;
            font-size: 32px;
            margin:10px 20px 10px 20px;
        }
        .club-content a {
            color: black;
            font-size: 22px;
            text-decoration: underline;
        }
        .team-name{
            font-size: 72px;
            font-weight: bold;
            padding-right: 10px;
            margin-bottom: -10px;
        }
    </style>

    <section class="our-webcoderskull padding-lg">

        <div class="container">

            <div class="club-info col-md-12">
                <div class="club-nav">
                    <div class="team-badge">
                        <img src="@Model.BadgeUrl" alt="alternate text"/>
                    </div>
                    <a class="btn btn-outline-secondary" asp-controller="Fixtures" asp-action="Club" asp-route-clubId="@Model.Id">Fixtures</a>
                    <a class="btn btn-outline-secondary" asp-controller="Supporters" asp-action="Club" asp-route-clubId="@Model.Id">Fans</a>
                </div>

                <div class="club-content">

                    <div>
                        <span class="team-name">@Model.Name</span>
                    </div>

                    <div>
                        <a href="@Model.SocialLinks.WebsiteLink">
                            <span>@Model.SocialLinks.WebsiteName</span>
                        </a>
                    </div>

                    <div class="team-sl">

                        <a href="@Model.SocialLinks.FacebookLink">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>

                        <a href="@Model.SocialLinks.TweeterLink">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>

                        <a href="@Model.SocialLinks.InstagramLink">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a>

                    </div>

                    <div>
                        Home:  @Model.StadiumName
                    </div>

                    <div>
                        <a href="@Model.PLLink">data source</a>
                    </div>

                </div>
            </div>

            <ul class="row container-players">

                @foreach (var player in Model.Players.Where(x=>x.SquadNumber != null).OrderByDescending(x => x.Position.Id).ThenBy(x=>int.Parse(x.SquadNumber)))
                {
                    <li class="col-12 col-md-6 col-lg-3 accept-policy" style="background-color:transparent">
                        <div class="cnt-block equal-hight border-bottom box-shadow" style="height: 389px;">

                            <span class="number">@player.SquadNumber</span>
                            <figure>
                                <img src="@player.ImageUrl" class="img-responsive" alt="" onerror="this.src = 'https://resources.premierleague.com/premierleague/photos/players/110x140/Photo-Missing.png'">
                            </figure>

                            <a class="btn button-player-card alert-success" asp-controller="UserGames" asp-action="AddPlayer" asp-route-id="@player.Id">
                                Buy
                            </a>

                            <p style="color:crimson">@player.PriceAtString</p>
                            <h3 class="display-2">@player.FullName</h3>
                            <p class="display-3">@player.PositionName <i style="color: grey"> @player.Country.Name</i></p>

                            <p>
                                <a class="btn btn-secondary alert-secondary" asp-controller="Players" asp-action="Points" asp-route-id="@player.Id">
                                    Points
                                </a>
                                <a class="btn btn-secondary alert-secondary" asp-controller="Players" asp-action="Profile" asp-route-id="@player.Id">
                                    Profile
                                </a>
                                <a class="btn btn-secondary alert-secondary" asp-controller="Players" asp-action="Statistics" asp-route-id="@player.Id">
                                    PL stats
                                </a>
                            </p>
                            <ul class="follow-us clearfix">
                                @if (player.SocialLinks.FacebookLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.FacebookLink">
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }
                                @if (player.SocialLinks.TweeterLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.TweeterLink">
                                            <i class="fa fa-twitter" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }
                                @if (player.SocialLinks.InstagramLink != null)
                                {
                                    <li>
                                        <a href="@player.SocialLinks.InstagramLink">
                                            <i class="fa fa-instagram" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                }

                            </ul>
                            <br />
                            <br />
                        </div>
                    </li>

                }
            </ul>

        </div> 

    </section>